### ISSUE TITLE
Suggested Multiplayer Demo Examples That Might Help The Ballistics (Free 3D Models)

### ISSUE THREAD

**Issue by WithinAmnesia** [XSnipinblazeX/GD-Ballistics#3]
This project is a really good start to helping the tank dev community work together to build a really good multiplayer tank game on Godot 4+.

Here is a list of some good 3D Godot multiplayer shooter demos.
https://github.com/TriggerCoder/Explosive-Salad (Godot 4 Shooter)
https://github.com/devloglogan/MultiplayerFPSTutorial (Godot 4 Shooter)
https://github.com/MrBocch/godot_tanks (Godot 4 Tanks)
https://github.com/tnibert/Panzer-Deathmatch-3D (Godot 3 though)
Extra Godot 4 multiplayer projects: https://github.com/WithinAmnesia/ARPG/discussions/16

I'll search more for CC0 3D models from itch.io, opengamesart and others.
https://danhs.itch.io/tank-garage (garage and Jagdtiger)
https://isolatedsoulstudio.itch.io/lowpoly-tank-pack-01 (Pz.Kpfw. IV is free)
https://opengameart.org/content/panzerkampfwagen-iii (Pz. III CC0)
https://opengameart.org/content/t-12-soviet-light-tank-lowpoly (T-12 CC0)
https://opengameart.org/content/lowpoly-soviet-jeep (WW2 Jeep CC0)
https://opengameart.org/content/industrial-building-1 (WW2 Industrial Factory Building CC0)
https://www.cgtrader.com/search?free=1&keywords=tank (Lots of free 3D tank models)
https://sketchfab.com/search?features=downloadable&licenses=7c23a1ba438d4306920229c12afcb5f9&licenses=72eb2b1960364637901eacce19283624&licenses=322a749bcfa841b29dff1e8a1bb74b0b&licenses=b9ddc40b93e34cdca1fc152f39b9f375&q=tank&type=models (Lots of free open source 3D tank models)
https://www.turbosquid.com/Search/Index.cfm?keyword=tank&media_typeid=2&min_price=0&max_price=0&page_num=1&sort=best_match (Lots of free 3D tank models)
All feedback and suggestions are welcome!

**Comment by XSnipinblazeX** [comment]
Closed so that this doesn't interfere with actual issues
